artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/krishnaik06/datasets/raw/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  train_path: artifacts/data_ingestion/samsum-train.csv
  test_path: artifacts/data_ingestion/samsum-test.csv
  val_path: artifacts/data_ingestion/samsum-validation.csv
  model:
  name: google/pegasus-cnn_dailymail

training:
  model_name: t5-small
  tokenizer_name: t5-small
  output_dir: artifacts/model
  num_train_epochs: 1
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1


